#include <stdio.h>

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:

 *		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 *
 */
 
int main() {
	int sum = 2;
	
	unsigned int fib1, fib2, fib3;
	
	fib1 = 1;
	fib2 = 2;
	fib3 = 3;
	
	while(fib3 < 4000000) {
		
		if(fib3 % 2 == 0) {
			sum += fib3;
			printf("%d\n", fib3);
		}
		
		fib1 = fib2;
		fib2 = fib3;
		
		fib3 = fib1 + fib2;
	}
	
	printf("%d", sum);
	return 0;
}
