#
# Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and 
# D = |Pk - Pj| is minimised; what is the value of D?
#
# Performance : 13,000ms
# Answer : 5,482,660
#

from eulerUtils import pentagonal_n
def p44():
    n = 2500
    pent = pentagonal_n(1, n, 'dict')
    pentSet = pentagonal_n(1, n, 'set')
    print 'starting loop..'

    for j in range(1, n):
        for k in range(j, n):
            if pent[k] - pent[j] in pentSet and pent[k] + pent[j] in pentSet:
                print k, j, pent[k], pent[j]
                return pent[k] - pent[j]

def init():
    print p44()